#!/usr/bin/env bash
# ============================================================
#  gen-agent-docs.sh — regenerate docs/agents/<name>.md for every
#  agent, from catalog + frontmatter. Fully automated; humans
#  never edit these (each carries a GENERATED header).
#  Run from repo root: bash scripts/factory/gen-agent-docs.sh
# ============================================================
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CATALOG="$ROOT/catalog/agents.tsv"
OUTDIR="$ROOT/docs/agents"
mkdir -p "$OUTDIR"

fm() { sed -n "s/^$2:[[:space:]]*//p" "$1" | head -n1; }
catfield() { # catfield <name> <col>
  awk -F'|' -v n="$1" -v i="$2" '
    /^#/ {next} { gsub(/^[ \t]+|[ \t]+$/,"",$1) }
    $1==n { gsub(/^[ \t]+|[ \t]+$/,"",$i); print $i; exit }
  ' "$CATALOG"
}

n=0
while IFS= read -r f; do
  [ -f "$f" ] || continue
  name="$(fm "$f" name)"
  [ -n "$name" ] || continue
  category="$(catfield "$name" 2)"
  type="$(catfield "$name" 3)"
  trigger="$(catfield "$name" 7)"
  tools="$(fm "$f" tools)"
  model="$(fm "$f" model)"
  src="${f#"$ROOT"/}"
  out="$OUTDIR/$name.md"
  {
    echo "<!-- GENERATED by scripts/factory/gen-agent-docs.sh — do not edit; edit $src + catalog/agents.tsv and regenerate. -->"
    echo "# $name"
    echo ""
    echo "| | |"
    echo "|---|---|"
    echo "| Category | \`$category\` |"
    echo "| Type | $type |"
    echo "| Model | \`${model:-inherit}\` |"
    echo "| Tools | \`${tools:-—}\` |"
    echo ""
    echo "**Fires when:** ${trigger:-—}"
    echo ""
    echo "Source of truth: [\`$src\`](../../$src) · catalog row in [\`catalog/agents.tsv\`](../../catalog/agents.tsv)."
    if [ "$type" = "gate" ]; then
      echo ""
      echo "> Read-only review gate — no Write/Edit tools by design. Returns the standard \`VERDICT: PASS | FAIL\` block."
    fi
  } > "$out"
  n=$((n + 1))
done <<EOF
$(find "$ROOT/.claude/agents" -type f -name '*.md' 2>/dev/null | sort)
EOF

echo "✅ generated $n agent doc page(s) in ${OUTDIR#"$ROOT"/}/"
