#!/usr/bin/env bash
# ============================================================
#  gen-index.sh — regenerate catalog/INDEX.md, the human-readable
#  master index of the whole crew, grouped by category, straight
#  from catalog/agents.tsv. Generated; never hand-edited.
#  Run from repo root: bash scripts/factory/gen-index.sh
# ============================================================
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CATALOG="$ROOT/catalog/agents.tsv"
OUT="$ROOT/catalog/INDEX.md"

total="$(awk -F'|' '/^#/{next} {gsub(/^[ \t]+|[ \t]+$/,"",$1)} $1!="" && $1!="name"{c++} END{print c+0}' "$CATALOG")"

{
  echo "<!-- GENERATED by scripts/factory/gen-index.sh — do not edit; edit catalog/agents.tsv and regenerate. -->"
  echo "# Crew Index"
  echo ""
  echo "**$total agents**, generated from \`catalog/agents.tsv\`. Every row here is a real file under \`.claude/agents/<category>/\`, validated by \`scripts/factory/validate-all.sh\` (0 orphans in either direction)."
  echo ""

  # categories in a stable, meaningful order
  for cat in core extended languages frameworks domains ops reviewers; do
    rows="$(awk -F'|' -v c="$cat" '
      /^#/{next}
      { for(i=1;i<=NF;i++) gsub(/^[ \t]+|[ \t]+$/,"",$i) }
      $1=="name"{next}
      $2==c && $1!="" { printf "| `%s` | %s | `%s` | %s |\n", $1, $3, $5, $7 }
    ' "$CATALOG")"
    [ -z "$rows" ] && continue
    ncat="$(printf '%s\n' "$rows" | grep -c '|')"
    echo "## $cat ($ncat)"
    echo ""
    echo "| Agent | Type | Model | Fires when |"
    echo "|---|---|---|---|"
    printf '%s\n' "$rows"
    echo ""
  done

  echo "---"
  echo ""
  echo "Regenerate: \`bash scripts/factory/gen-index.sh\`. Per-agent doc pages: \`docs/agents/<name>.md\` (\`gen-agent-docs.sh\`)."
} > "$OUT"

echo "✅ wrote ${OUT#"$ROOT"/} — $total agents indexed"
