#!/usr/bin/env bash
# test-export-agents.sh — AGENTS.md generated with workflow + all roles.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

fails=0
check() {
  if [ "$3" -eq "$2" ]; then printf '     ok: %s\n' "$1"
  else printf '   FAIL: %s (expected %s, got %s)\n' "$1" "$2" "$3"; fails=$((fails + 1)); fi
}
has() { # has <desc> <pattern> <file>
  if grep -q "$2" "$3" 2>/dev/null; then printf '     ok: %s\n' "$1"
  else printf '   FAIL: %s (pattern not found: %s)\n' "$1" "$2"; fails=$((fails + 1)); fi
}

SB="$(mktemp -d)"
trap 'rm -rf "$SB"' EXIT

# export against a --full installed scratch project (the realistic case)
git -C "$SB" init -q
( cd "$SB" && bash "$ROOT/install.sh" --full >/dev/null 2>&1 )
( cd "$SB" && CLAUDE_PROJECT_DIR="$SB" bash "$SB/.thekedar/scripts/export-agents-md.sh" >/dev/null 2>&1 ); code=$?
check "export exits 0" 0 "$code"

OUT="$SB/AGENTS.md"
[ -f "$OUT" ] || { printf '   FAIL: AGENTS.md not written\n'; exit 1; }

has "generated marker present" "GENERATED by thekedar" "$OUT"
has "iron loop section" "## The iron loop" "$OUT"
has "file contracts section" "## File contracts" "$OUT"
has "crew table section" "## The crew" "$OUT"
has "scope-addition rule survives" "Scope addition" "$OUT"
has "fix-loop cap survives" "Max 3 fix loops" "$OUT"
has "honest note about self-review" "grades its own homework" "$OUT"

n=$(grep -c '^### Role: ' "$OUT")
check "all 15 roles exported" 15 "$n"
for a in planner backend-dev frontend-dev error-checker security-auditor frontend-reviewer \
         test-writer db-specialist api-designer docs-writer performance-auditor \
         accessibility-auditor dependency-auditor devops-engineer refactor-specialist; do
  grep -q "^### Role: $a$" "$OUT" || { printf '   FAIL: role missing: %s\n' "$a"; fails=$((fails + 1)); }
done
printf '     ok: every named role present\n'

has "gate verdict format survives flattening" "VERDICT: PASS | FAIL" "$OUT"

# custom output path works
( cd "$SB" && CLAUDE_PROJECT_DIR="$SB" bash "$SB/.thekedar/scripts/export-agents-md.sh" "$SB/CUSTOM.md" >/dev/null 2>&1 ); code=$?
check "custom output path exits 0" 0 "$code"
if [ -f "$SB/CUSTOM.md" ]; then
  printf '     ok: custom output path written\n'
else
  printf '   FAIL: custom output missing\n'; fails=$((fails + 1))
fi

exit "$fails"
