#!/usr/bin/env bash
# ============================================================
#  export-agents-md.sh — F10: the AGENTS.md export
#  Usage (from a project with thekedar installed, or this repo):
#    bash .thekedar/scripts/export-agents-md.sh [output-path]
#
#  Flattens the Thekedar workflow into a single AGENTS.md for
#  tools without subagent isolation (Cursor, Codex CLI, Copilot,
#  Windsurf, ...): one context follows the same plan → build →
#  review → log loop sequentially. Weaker isolation, same
#  discipline, same files on disk.
#
#  Crew sections are GENERATED from the agent .md files —
#  edit those, re-run this, never hand-edit the output.
# ============================================================
set -u

PROJ="${CLAUDE_PROJECT_DIR:-$(pwd)}"
OUT="${1:-$PROJ/AGENTS.md}"
AGENTS_DIR="$PROJ/.claude/agents"

if [ ! -d "$AGENTS_DIR" ]; then
  echo "❌ $AGENTS_DIR not found — run install.sh first (or run from the thekedar repo)." >&2
  exit 1
fi

# frontmatter field reader: fm <file> <key>
fm() { sed -n "s/^$2: //p" "$1" | head -n1; }
# description: > block — collect indented lines after the key
fm_desc() {
  awk '/^description: >/{grab=1; next} grab && /^  /{sub(/^  /,""); printf "%s ", $0; next} grab{exit}' "$1"
}
# body after the closing --- of frontmatter
body() { awk 'c>=2{print} /^---$/{c++}' "$1"; }

{
cat <<'HEADER'
# AGENTS.md — the Thekedar workflow (single-context mode)

> GENERATED by thekedar's export-agents-md.sh — do not hand-edit; re-run the export.
> Source of truth: .claude/agents/*.md + the thekedar skill.
>
> This file encodes the Thekedar site-supervisor discipline for agents WITHOUT
> subagent isolation (Cursor, Codex CLI, Copilot, Windsurf, ...). You are one
> context playing every role IN SEQUENCE. The isolation is weaker than Claude
> Code's separate context windows — the discipline and the paper trail are the same.

## The iron loop

For any request bigger than one file / ~30 lines: NEVER just start coding.

1. **PLAN** — act as the planner (below): write small task files to
   `.thekedar/tasks/NNN-slug.md` (use `.thekedar/templates/task.md`). Each task:
   concrete In-scope, mandatory NOT-in-scope fence, 2–5 verifiable acceptance
   criteria, Expected files, Risk, Estimated size. Update .thekedar/PROJECT_STATE.md.
2. **BUILD one task** — mark exactly ONE task ACTIVE. Act as the matching doer
   (below). Touch ONLY the task's Expected files; genuinely need another file →
   append a `## Scope addition` entry (file + one-line reason) to the task file
   FIRST, then edit.
3. **REVIEW** — switch roles: act as error-checker, then security-auditor (then
   frontend-reviewer if UI files changed; dependency-auditor if manifests changed).
   Play each honestly — you did NOT write this code. Produce each gate's VERDICT
   block. Any FAIL → fix as the doer, re-review. Max 3 fix loops, then STOP and
   show the human the raw findings.
4. **LOG + CHECKPOINT** — write `.thekedar/changes/task-NNN.md` (what changed /
   what was deliberately NOT changed / why / verdicts). Append every edited file
   to `.thekedar/changes/ledger-<date>.md` as `| time | tool | path |`. Update
   PROJECT_STATE.md. `git add -A && git commit -m "thekedar(task-NNN): <title>"`.
5. Next task → back to 2. Session ends mid-project → PROJECT_STATE.md is the
   resume point; read it first next session, reconcile with `git log`, continue.

Trivial request (single file, < ~30 lines, pure question)? Skip all of it — say
`[thekedar: skipped — trivial]` and just do it.

## File contracts (do not improvise formats)

- Task: Objective · In scope · NOT in scope · Acceptance criteria (checkboxes) ·
  Expected files · Status (TODO|ACTIVE|REVIEW|DONE|BLOCKED) · Risk · Estimated size
- PROJECT_STATE: overview · current phase · phases (if big) · active task · done ·
  up next · decisions log (append-only) · known issues
- Changelog: what changed · what was deliberately NOT changed (mandatory, honest) ·
  why · files touched · verification (verdicts + drift note) · follow-ups

HEADER

echo "## The crew (role reference)"
echo ""
echo "| Role | Type | Model hint | Tools discipline |"
echo "|---|---|---|---|"
for f in "$AGENTS_DIR"/core/*.md "$AGENTS_DIR"/extended/*.md "$AGENTS_DIR"/custom/*.md; do
  [ -f "$f" ] || continue
  name="$(fm "$f" name)"
  model="$(fm "$f" model)"
  tools="$(fm "$f" tools)"
  case "$tools" in
    *Write*|*Edit*) type="doer/brain" ;;
    *)              type="gate (read-only)" ;;
  esac
  printf '| %s | %s | %s | %s |\n' "$name" "$type" "${model:-inherit}" "${tools:-—}"
done
echo ""
echo "When a step below says \"act as X\", adopt that role's rules verbatim:"
echo ""

for f in "$AGENTS_DIR"/core/*.md "$AGENTS_DIR"/extended/*.md "$AGENTS_DIR"/custom/*.md; do
  [ -f "$f" ] || continue
  name="$(fm "$f" name)"
  echo "---"
  echo ""
  echo "### Role: $name"
  echo ""
  desc="$(fm_desc "$f")"
  [ -n "$desc" ] && { echo "> When: $desc"; echo ""; }
  body "$f"
  echo ""
done

cat <<'FOOTER'
---

## Honest note

Single-context mode grades its own homework — the reviewer roles share your
memory and your blind spots. It still beats no review, and the paper trail
(tasks, ledger, changelogs, PROJECT_STATE) is identical to full Thekedar.
For real context isolation, use Claude Code with subagents: the reviewer
that never saw the code being written finds what you cannot.
FOOTER
} > "$OUT"

lines="$(wc -l < "$OUT" | tr -d ' ')"
agents="$(grep -c '^### Role: ' "$OUT")"
echo "✅ wrote $OUT — $agents roles, $lines lines"
exit 0
