#!/usr/bin/env bash
# ============================================================
#  report.sh — F17-lite: the written hisaab
#  Usage, from your project root:
#    bash .thekedar/scripts/report.sh [output-path]
#
#  Compiles PROJECT_STATE + every task changelog + ledger stats
#  + git checkpoints into one REPORT.md. Derived data — safe to
#  regenerate anytime; the .thekedar/ sources stay the truth.
# ============================================================
set -u

PROJ="${CLAUDE_PROJECT_DIR:-$(pwd)}"
OUT="${1:-$PROJ/REPORT.md}"
TK="$PROJ/.thekedar"

if [ ! -d "$TK" ]; then
  echo "❌ no .thekedar/ here — nothing to report." >&2
  exit 1
fi

# ---- counts (facts from files, never estimates) ----
tasks_total=0; tasks_done=0; tasks_blocked=0
for t in "$TK/tasks"/*.md; do
  [ -f "$t" ] || continue
  tasks_total=$((tasks_total + 1))
  grep -q '^\*\*Status:\*\* DONE'    "$t" && tasks_done=$((tasks_done + 1))
  grep -q '^\*\*Status:\*\* BLOCKED' "$t" && tasks_blocked=$((tasks_blocked + 1))
done

edits=0; files_touched=0
if ls "$TK/changes"/ledger-*.md >/dev/null 2>&1; then
  edits="$(grep -h '^|' "$TK/changes"/ledger-*.md 2>/dev/null \
           | grep -cv -e '^| Time' -e '^|---' || true)"
  files_touched="$(grep -h '^|' "$TK/changes"/ledger-*.md 2>/dev/null \
                   | grep -v -e '^| Time' -e '^|---' \
                   | awk -F'|' '{gsub(/^ +| +$/,"",$4); if ($4!="") print $4}' \
                   | sort -u | wc -l | tr -d ' ')"
fi

fix_loops=0
for c in "$TK/changes"/task-*.md; do
  [ -f "$c" ] || continue
  n="$(sed -n 's/.*Fix loops used:\*\* *\([0-9]*\).*/\1/p; s/.*Fix loops used: *\([0-9]*\).*/\1/p' "$c" | head -n1)"
  [ -n "$n" ] && fix_loops=$((fix_loops + n))
done

changelogs="$(find "$TK/changes" -maxdepth 1 -name 'task-*.md' 2>/dev/null | wc -l | tr -d ' ')"

# ---- compose ----
{
  echo "# Project report — $(basename "$PROJ")"
  echo ""
  echo "> Generated by thekedar report.sh on $(date '+%Y-%m-%d %H:%M'). Derived from"
  echo "> \`.thekedar/\` — regenerate anytime; the sources are the truth."
  echo ""
  echo "## Numbers (counted, not estimated)"
  echo ""
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Tasks done | $tasks_done / $tasks_total |"
  echo "| Tasks blocked | $tasks_blocked |"
  echo "| Edits logged (munshi) | $edits |"
  echo "| Unique files touched | $files_touched |"
  echo "| Fix loops used | $fix_loops |"
  echo "| Task changelogs | $changelogs |"
  echo ""

  if [ -f "$TK/PROJECT_STATE.md" ]; then
    echo "## Current state"
    echo ""
    cat "$TK/PROJECT_STATE.md"
    echo ""
  fi

  if [ "$changelogs" -gt 0 ]; then
    echo "## Task-by-task record"
    echo ""
    for c in "$TK/changes"/task-*.md; do
      [ -f "$c" ] || continue
      cat "$c"
      echo ""
      echo "---"
      echo ""
    done
  fi

  echo "## Edit activity (ledger days)"
  echo ""
  if ls "$TK/changes"/ledger-*.md >/dev/null 2>&1; then
    echo "| Day | Edits |"
    echo "|---|---|"
    for l in "$TK/changes"/ledger-*.md; do
      day="$(basename "$l" .md)"; day="${day#ledger-}"
      n="$(grep -c '^|' "$l" 2>/dev/null || echo 0)"
      [ "$n" -ge 2 ] && n=$((n - 2))   # minus header rows
      echo "| $day | $n |"
    done
  else
    echo "_No ledger files yet._"
  fi
  echo ""

  echo "## Git checkpoints"
  echo ""
  if command -v git >/dev/null 2>&1 && git -C "$PROJ" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo '```'
    git -C "$PROJ" log --oneline -30 2>/dev/null || echo "(no commits yet)"
    echo '```'
  else
    echo "_Not a git repository — checkpoints unavailable._"
  fi
} > "$OUT"

echo "✅ wrote ${OUT#"$PROJ"/} — $tasks_done/$tasks_total tasks, $edits edits, $fix_loops fix loops"
exit 0
